spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/affitto_case
spring.datasource.username=root
spring.datasource.password=Mattia1207!Root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:clienti.sql, classpath:offerte.sql, classpath:stanze.sql, classpath:recensioni.sql, classpath:prenotazione.sql

# Configurazione Email (Sostituisci con l'email del tuo B&B)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ragusamat@gmail.com
spring.mail.password=sifc gipa mvjs kjnr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
